### ISSUE TITLE
[Docs] 路径问题

### ISSUE THREAD

**Issue by sakura-001-wjx** [OpenGVLab/InternVL#916]
### 📚 The doc issue

您好！在对internVL2.5-4b模型进行微调时，我注意到在下载hugging face上面官方给的权重后，还需要在pretained里面下载哪些问题呢，以及这些文件放置的位置，我下载了internvl和internvl_chat，在运行的时候会报错：[INFO|tokenization_auto.py:606] 2025-02-21 18:50:59,802 >> Could not locate the tokenizer configuration file, will try to use the model config instead.

**Comment by Sakura-not-sleep** [comment]
> hi, 可以提供你的运行文件吗？

不用了已经解决了，谢谢！但是现在还有一个问题，现在我把我的数据集输入进InternVL2.5后，大概有10%左右的视频会出现如下报错：decord._ffi.base.DECORDError: [21:21:05] /github/workspace/src/video/video_reader.cc:486: Error: av_read_frame failed with 1094995529。目前无法解决，请问这个有具体解决方法吗，我的微信是18234210977，我们可以联系一下，非常感谢！

**Comment by lll2343** [comment]
10%的话读不了，会不会是你的这部分视频文件已经损坏了呢，可以检查一下这个

**Comment by Sakura-not-sleep** [comment]
> 10%的话读不了，会不会是你的这部分视频文件已经损坏了呢，可以检查一下这个

并没有，视频可以正常查看，并且我重新上传了几次还是会报错
